<?php

namespace App\Http\Sections;

use App\User;
use AdminColumn;
use AdminDisplay;
use AdminForm;
use AdminFormElement;
use SleepingOwl\Admin\Contracts\DisplayInterface;
use SleepingOwl\Admin\Contracts\FormInterface;
use SleepingOwl\Admin\Contracts\Initializable;
use SleepingOwl\Admin\Section;

class Users extends Section implements Initializable
{
    /**
     * @var bool
     */
    protected $checkAccess = false;

    /**
     * @var string
     */
    protected $title;

    /**
     * @var string
     */
    protected $alias;

    /**
     * @return DisplayInterface
     */
    public function getTitle()
    {
        return 'Працівники'; // TODO: Change the autogenerated stub
    }

    public function getIcon()
    {
        return 'fa fa-group';
    }
    public function onDisplay()
    {
        return AdminDisplay::datatables()
            ->with('role')
            ->setHtmlAttribute('class', 'table-primary')
            ->setColumns(
                AdminColumn::text('id', '#')
                    ->setWidth('30px'),
                AdminColumn::image('avatar', '')
                    ->setOrderable(false)
//                    ->setImageWidth('25px')
                ,
                AdminColumn::text('name', 'Ім\'я'),
                AdminColumn::text('phone', 'Телефон'),
                AdminColumn::email('email', 'Em@il'),
                AdminColumn::text('role.alias','Статус'),
                AdminColumn::datetime('created_at','Створено')
                    ->setFormat('d.m.Y')
            )->paginate(20);
    }

    /**
     * @param int $id
     *
     * @return FormInterface
     */
    public function onEdit($id)
    {
        return AdminForm::panel()->addBody([
            AdminFormElement::image('avatar', 'ava'),
            AdminFormElement::text('name', 'Key')->required(),
            AdminFormElement::text('phone', 'Телефон'),
            AdminFormElement::text('email', 'Email')->required(),
        ]);
    }

    /**
     * @return FormInterface
     */
    public function onCreate()
    {
//        return $this->onEdit(null);
    }

    /**
     * @return void
     */
    public function onDelete($id)
    {
        // todo: remove if unused
    }

    /**
     * @return void
     */
    public function onRestore($id)
    {
        // todo: remove if unused
    }

    /**
     * Initialize class.
     */
    public function initialize()
    {
        $this->addToNavigation($priority = 500, function() {
            return \App\User::count();
        });
    }
}
